
###
POST http://192.168.18.64:8000/api/user/schoolAdminlogin
Content-Type: application/json

{
  "email": "aneeshassayyn1299@gmail.com",
 "password":"66666"
}

###
GET  http://192.168.18.64:8000/api/user/loggedSchoolAdmin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MmI3NzFmMGQ3YTU4ZjlhMjgxZGRiZWMiLCJpYXQiOjE2NTYyNTk0MzUsImV4cCI6MTY1NjY5MTQzNX0.KqQ0edvAkVv66tV-cOZrztKzeCs3oGB61G-sY6FLU_4


###

POST http://192.168.18.64:8000/api/user/registerTeacher
Content-Type: application/json

{
  "image": "image",
 "first_name": "first_name",
 "last_name": "last_name",
              "email": "email@gmail.com",
              "password": "444444",
              "confirm_password" : "444444",
              "contact": "44353",
              "alt_contact": "3453543",
              "address_1": "address_1",
              "address_2": "address_2",
              "cnic": "443445434",
              "city": "city"
}

###
POST http://192.168.18.26:8000/api/user/teachersLogin
Content-Type: application/json

{
  "email": "email@gmail.com",
 "password":"444444"
}


###
GET  http://192.168.18.26:8000/api/user/loggedTeachers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MmI5NjYxZjY2OWQyZjIwNjdhMGJhMmIiLCJpYXQiOjE2NTY0MTQ0NjQsImV4cCI6MTY1Njg0NjQ2NH0.0B3EBycxVnSWMY8bFegFYZe7tNoJMd1irSnaz-E29kE

###
GET  http://192.168.18.14:8000/api/user/getTeachers

###
GET  http://192.168.18.64:8000/api/user/getschools

###
POST http://192.168.18.14:8000/api/user/createschool
Content-Type: application/json

{
 "school_name": "adfjldska",
              "contact_no": "44353",
              "address_1": "address_1",
              "address_2": "address_2",
              "district" : "district",
              "province" : "province",
              "city": "city"
}
GET http://192.168.18.64:8000/api/user/getstudent
