
###
POST http://192.168.18.64:8000/api/user/schoolAdminlogin
Content-Type: application/json

{
  "email": "aneeshassayyn1299@gmail.com",
 "password":"66666"
}

###
GET  http://192.168.18.12:8000/api/user/loggedSchoolAdmin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MmI3NzFmMGQ3YTU4ZjlhMjgxZGRiZWMiLCJpYXQiOjE2NTY1ODIzMTUsImV4cCI6MTY1NzAxNDMxNX0.6kdNgqyDzwtq7BJN_Jk9xg0FA1ttByzjMYlYRfHXIAM

###

POST http://192.168.18.64:8000/api/user/createstudent
Content-Type: application/json

{
  "schoolName" : "adfasdadf",
  "schoolId" : "4834543",
  "image": "image",
 "first_name": "first_name",
 "last_name": "last_name",
              "father_name": "adfd@gmail.com",
              "father_cnic": "443454444",
              "emergency_contact" : "444345444",
              "contact": "44353",
              "address_1": "address_1",
              "address_2": "address_2",
              "city": "city",
              "roll_no" : "roll_no",
              "student_class" : "student_class",
              "section": "section"
}

###

POST http://192.168.18.26:8000/api/user/createschool
Content-Type: application/json

{
  "address_1": "Hsbz",  
  "address_2": "Hzhz",  
  "categories":"strong",      
  "level": "sef",
  "partnername": "Vsvs",
  "school_name": "Hahs",
  "schoolcode": "123",
  "selectedDistricts": "Jamshoro District",
  "selectedTehsil": "Khoski Tehsil",
  "uc": "Hsbd",
  "village": "Bzbz"
  }

###
POST http://192.168.18.26:8000/api/user/teachersLogin
Content-Type: application/json

{
  "email": "email@gmail.com",
 "password":"444444"
}


###
GET  http://192.168.18.26:8000/api/user/loggedTeachers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MmI5NjYxZjY2OWQyZjIwNjdhMGJhMmIiLCJpYXQiOjE2NTY0MTQ0NjQsImV4cCI6MTY1Njg0NjQ2NH0.0B3EBycxVnSWMY8bFegFYZe7tNoJMd1irSnaz-E29kE

###
GET  http://192.168.18.14:8000/api/user/getTeachers

###
GET  http://192.168.18.26:8000/api/user/getstudentsattendancedashboard

###
GET  http://192.168.18.12:8000/api/user/getteacherattendancedashboardbyteacherid/62c54aadc3027cd453dd357a

###
GET  http://192.168.18.26:8000/api/user/getstudentsattendancedashboardbyschoolid/62c542db114bdf03a6800210


###
GET  http://192.168.18.14:8000/api/user/getteacherattendance/62c54aadc3027cd453dd357a

###
GET  http://192.168.18.26:8000/api/user/getschools

###
GET  http://192.168.18.26:8000/api/user/getSchoolAdmin

###
POST http://192.168.18.14:8000/api/user/createschool
Content-Type: application/json

{
 "school_name": "adfjldska",
              "contact_no": "44353",
              "address_1": "address_1",
              "address_2": "address_2",
              "district" : "district",
              "province" : "province",
              "city": "city"
}

###
GET http://192.168.18.64:8000/api/user/getstudent

###
POST  http://192.168.18.14:8000/api/user/schooladmin
Content-Type: application/json

{
  "S_NO": "6494",
  "alt_contact": "8797",
  "cnic": "979797",
  "confirm_password": "1234",
  "contact": "9797",
  "dateofbirth": "2022-07-26",
  "email": "Vsvsvs@gmail.com",
  "father_husband": "Vzvz",
  "first_name": "Gsvs",
  "gender": "Male",
  "image": "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540mehdi_hasan%252FReactNativeAuthUI1/ImagePicker/312772bd-43b6-4cad-983a-f41d4e97b62b.mp4",
  "last_name": "Gsgs",
  "maritalStatus": "Married",
  "password": "1234",
  "religion": "Muslim",
  "schoolId": "62c542db114bdf03a6800210",
  "schoolName": "The Educators",
  "selectedDistricts": "Badin",
  "teacherQualification":  [
    "Metric"
  ],
  "teacherprofessionalqualification":  [
    "B.ED"
  ]
}

###

GET  http://192.168.18.64:8000/api/user/getStudents/62bd734cd42e6cb70ce8187b

###
GET  http://192.168.18.64:8000/api/user/getschoolAdmin/62bd734cd42e6cb70ce8187b

###
GET  http://192.168.18.64:8000/api/user/getSomestudents/62c3ffe678f31b84bdda241e

###
GET  http://192.168.18.64:8000/api/user/getSometeacher/62c3ffe678f31b84bdda241e



###
GET  http://192.168.10.6:8000/api/user/getTeachers

###
POST http://192.168.18.64:8000/api/user/teacherattendance
Content-Type: application/json

 [
 {
    "id": "62bda0dc8983ac4ba784851d",
    "attendance": "L",
    "first_name": "gghu",
    "last_name":"jj",
    "schoolAdminId": "62bd73bbd42e6cb70ce81882",
    "schoolId": "62bd734cd42e6cb70ce8187b"
  },
  {
    "id": "62bda0dc8983ac4ba784851dljjsk",
    "attendance": "L",
    "first_name": "ggmhhu",
    "last_name":"jmjjj",
    "schoolAdminId": "62bd73jhgbbd42e6cb70ce81882",
    "schoolId": "62bd734cd42ekh6cb70ce8187b"
  }

]
  

###
POST http://192.168.18.64:8000/api/user/registerTeacher
Content-Type: application/json

 {
  "selectDivision": "selectDivision",
              "selectedDistricts": "selectedDistricts",
              "seletctedTehsil": "seletctedTehsil",
              "schoolName":"schoolName",
              "staffName":"staffName",
              "gender":"gender",
              "religion":"religion",
              "maritalStatus":"maritalStatus",
              "formerProgramm":"formerProgramm",
              "teacherQualification":"teacherQualification",
              "teacherProfessionalQualification":"teacherProfessionalQualification",
              "teacherTraining":"teacherTraining",
              "lsuTrainingDate":"lsuTrainingDate",
              "trainInWhichSubject":"trainInWhichSubject",
              "mentiontraining":"mentiontraining",
              "trainingNumber":"trainingNumber",
              "cnic":"cnic",
              "address_1":"address_1",
              "address_2":"address_2",
              "father_Name":"father_Name",
              "email":"email",
              "password":"123",
              "confirm_password":"123",
              "contact":"contact",
              "alt_contact":"alt_contact",
              "schoolId":"schoolId",
              "image" :"image",
              "staffPosition":"staffPosition",
              "teachingClass":"teachingClass",
              "subjectSpeciality":"subjectSpeciality",
              "SubjectSpec":"SubjectSpec",
              "teachingmedium":"teachingmedium",
              "teachingExperience":"teachingExperience",
              "experienceDuration":"experienceDuration",
              "dateofbirth":"dateofbirth",
              "dateofJoining":"dateofJoining",
              "contractstart":"contractstart",
              "contractend":"contractend",
              "vaccinated":"vaccinated",
              "vaccineshots":"vaccineshots",
              "vacinatedstatus":"vacinatedstatus",
              "startingSalary":"startingSalary",
              "currentSalary":"currentSalary",
              "salaryPaymentMethod":"salaryPaymentMethod",
              "bankname":"bankname",
              "accounttitle":"accounttitle",
              "bankdistrict":"bankdistrict",
              "bankcity":"bankcity",
              "ibanAccount":"ibanAccount",
              "bankaccountnumber":"bankaccountnumber",
              "schoolstaff":"schoolstaff",
              "teachingSubject":"teachingSubject"
}